name: flutube
description: Flutter plugin that facilitates the embed of YT videos without using the official YT API.
version: 1.0.0
author: Javi Hurtado <webmaster@javi-h.com>
homepage: https://github.com/ja2375/FluTube

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  webview_flutter: ^0.3.7+1
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/yt_player.html