name: flutube
description: Flutter plugin that facilitates the embed of YT videos without using the official YT API.
version: 0.8.1
author: Javi Hurtado <webmaster@javi-h.com>
homepage: https://github.com/ja2375/FluTube

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ">= 0.12.0 <0.13.0"
  youtube_extractor: ^1.0.4
  cached_network_image: ^2.0.0-rc
  chewie:
    git: 
      url: https://github.com/puzuka/chewie.git
      ref: 7eb0f7effebd6217717e627a1cf61f29579f9d8a
  flutter:
    sdk: flutter

flutter:
  assets:
   - assets/images/
   - assets/images/icons/
